[package]
name = "assignment_five"
version = "0.1.0"
authors = ["Ankit Mogha <ankit.mogha@knoldus.com>"]
edition = "2018"

# See more keys and their definitions at https://doc.rust-lang.org/cargo/reference/manifest.html

[dependencies]
